# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LSBcipherdecode.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class LSBDecodeUI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(384, 505)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.previewButton = QtWidgets.QPushButton(self.centralwidget)
        self.previewButton.setGeometry(QtCore.QRect(260, 50, 91, 33))
        self.previewButton.setObjectName("previewButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 211, 21))
        self.label.setObjectName("label")
        self.pathEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.pathEdit.setGeometry(QtCore.QRect(40, 50, 171, 31))
        self.pathEdit.setObjectName("pathEdit")
        self.previewLabel = QtWidgets.QLabel(self.centralwidget)
        self.previewLabel.setGeometry(QtCore.QRect(50, 120, 101, 91))
        self.previewLabel.setObjectName("previewLabel")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 101, 17))
        self.label_2.setObjectName("label_2")
        self.decodeButton = QtWidgets.QPushButton(self.centralwidget)
        self.decodeButton.setGeometry(QtCore.QRect(190, 160, 141, 41))
        self.decodeButton.setObjectName("decodeButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 220, 54, 17))
        self.label_3.setObjectName("label_3")
        self.lineEdit_r = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_r.setGeometry(QtCore.QRect(40, 240, 113, 33))
        self.lineEdit_r.setObjectName("lineEdit_r")
        self.lineEdit_rr = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_rr.setGeometry(QtCore.QRect(40, 300, 113, 33))
        self.lineEdit_rr.setObjectName("lineEdit_rr")
        self.lineEdit_gr = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_gr.setGeometry(QtCore.QRect(230, 300, 113, 33))
        self.lineEdit_gr.setObjectName("lineEdit_gr")
        self.lineEdit_g = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_g.setGeometry(QtCore.QRect(230, 240, 113, 33))
        self.lineEdit_g.setObjectName("lineEdit_g")
        self.lineEdit_b = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_b.setGeometry(QtCore.QRect(40, 380, 113, 33))
        self.lineEdit_b.setObjectName("lineEdit_b")
        self.lineEdit_br = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_br.setGeometry(QtCore.QRect(40, 440, 113, 33))
        self.lineEdit_br.setObjectName("lineEdit_br")
        self.lineEdit_rgb = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_rgb.setGeometry(QtCore.QRect(230, 380, 113, 33))
        self.lineEdit_rgb.setObjectName("lineEdit_rgb")
        self.lineEdit_rgbr = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_rgbr.setGeometry(QtCore.QRect(230, 440, 113, 33))
        self.lineEdit_rgbr.setObjectName("lineEdit_rgbr")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 280, 91, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(240, 280, 101, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(240, 220, 54, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 360, 54, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(240, 360, 54, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(50, 420, 81, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(240, 420, 81, 17))
        self.label_10.setObjectName("label_10")
        self.fileExplorerButton = QtWidgets.QPushButton(self.centralwidget)
        self.fileExplorerButton.setGeometry(QtCore.QRect(220, 50, 31, 33))
        self.fileExplorerButton.setObjectName("fileExplorerButton")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(60, 80, 141, 17))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LSBcipher decode mode"))
        self.previewButton.setText(_translate("MainWindow", "Preview"))
        self.label.setText(_translate("MainWindow", "Print full path to your image here:"))
        self.previewLabel.setText(_translate("MainWindow", "Preview"))
        self.label_2.setText(_translate("MainWindow", "Image preview:"))
        self.decodeButton.setText(_translate("MainWindow", "Decode LSB message"))
        self.label_3.setText(_translate("MainWindow", "Red"))
        self.label_4.setText(_translate("MainWindow", "Red reversed"))
        self.label_5.setText(_translate("MainWindow", "Green reversed"))
        self.label_6.setText(_translate("MainWindow", "Green"))
        self.label_7.setText(_translate("MainWindow", "Blue"))
        self.label_8.setText(_translate("MainWindow", "RGB"))
        self.label_9.setText(_translate("MainWindow", "Blue reversed"))
        self.label_10.setText(_translate("MainWindow", "RGB reversed"))
        self.fileExplorerButton.setText(_translate("MainWindow", "F"))
        self.label_1.setText(_translate("MainWindow", "*working only with png/bmp/jpg etc"))

